site:
  title: Sorryfu Blog
  description: 这个人很懒，什么也没留下
  create_post: https://github.com/FuShaoLei/auto-blog/new/master/source/_posts #创建新文章时用到
  edit_post: https://github.com/FuShaoLei/auto-blog/edit/master/source/_posts/ #修改文章的时候会用到
  foot: Theme by [Slate](https://github.com/FuShaoLei/hexo-theme-slate) Power by [Hexo](https://hexo.io/)

menu:
  主页: /
  友链: /friend
  开往: https://travellings.now.sh/

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.2.0/styles/a11y-dark.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles