site:
  title: Sorryfu Blog
  description: 这个人很懒，什么也没留下
  create_post: https://github.com/FuShaoLei/auto-blog/new/master/source/_posts #创建新文章时用到
  edit_post: https://github.com/FuShaoLei/auto-blog/edit/master/source/_posts/ #修改文章的时候会用到
  edit_page: https://github.com/FuShaoLei/auto-blog/edit/master/source/ #修改页面时用到
  foot: Theme by [Slate](https://github.com/FuShaoLei/hexo-theme-slate) Power by [Hexo](https://hexo.io/)

menu:
  主页: /
  关于: /about
  友链: /friend
  开往: https://travellings.now.sh/

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.2.0/styles/a11y-dark.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles


# 评论系统设置
comments:
  open: true #是否开启评论系统
  system: gitalk #选择评论系统 可选 valine gitalk livere
  # Valine
  valine:
    appid: #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  # Gitalk
  gitalk:
    owner: FuShaoLei #Github 用户名,
    repo: FuShaoLei.github.io #储存评论issue的github仓库名
    admin: FuShaoLei  #Github 用户名
    clientID: 6c819bd8bda4595860b0  #`Github Application clientID`
    clientSecret: 55472986bef24cdbd1ad2b527530d2e613ea8679 #`Github Application clientSecret`
  #livere
  livere: # 前往 http://livere.com/ 申请账号
    dataId: city #免费版本city
    dataUid: #安装代码中 data-uid 后面数据